---
# Cleanup and report  
- name: Check if the long-running job is done and cleanup
  ansible.builtin.async_status:
    jid: "{{ async_job_result.ansible_job_id }}"
    mode: cleanup

- name: Stop all running Lino processes
  ansible.builtin.shell: "pkill -f 'lino *'"
  become: true
  failed_when: false # Don't fail if no process is found