---
- name: Clear the named pipes {{ item }}
  command: rm -f {{ item }}
  ignore_errors: true

- name: Create the named pipe {{ item }}
  command: mkfifo --m 666 {{ item }}
  args:
    creates: "{{ item }}"