---
- name: "Execute LINO Pull : {{ idName }}"
  shell: |
    lino pull source -l 10 -i {{ descriptor }} > {{ pipeOut }}
  args:
    executable: /bin/bash
  register: pull_result
 

- name:  "Log - Pull : {{ idName }}"
  debug:
    var: pull_result
